Maria Saganovich - Lesson 12 hw
eugene-okulik/QAP-05 pull request #11
Opened 2022-02-08 12:14 UTC by maryiasa

2022-02-08 12:25 UTC, eugene-okulik requested changes
Один комментарий - просто комментарий )), а остальные два в местах, где ответ нужно чуть подправить.

2022-02-08 12:25 UTC, eugene-okulik commented on personal_dirs/maryiasa/lesson_12/lesson12_HW.txt
> +
Ого, как много!

2022-02-08 12:25 UTC, eugene-okulik commented on personal_dirs/maryiasa/lesson_12/lesson12_HW.txt
> +
Приемочное - это не из деления по уровням. Деление по уровням - чисто теоретическое. А приемочное тестирование это уже более практческая деятельность. В рамках приемочного тестирования могут проводить как модульное, так и интеграционное, так и системное тестирование. Например, заказчик может проверять только добавленную фичу (модульное), а может прогонять и полноценное тестирование всей системы (системное)

2022-02-08 12:25 UTC, eugene-okulik commented on personal_dirs/maryiasa/lesson_12/lesson12_HW.txt
> +Возможность изменения стратегии, подходов в процессе работы над продуктом, дабы он оставался конкурентоспособным.
При рассказе про Agile важно упоминать разбиение на спринты и постепенное наращивание функционала.

2022-02-09 17:33 UTC, maryiasa commented on personal_dirs/maryiasa/lesson_12/lesson12_HW.txt
> +
fixed

2022-02-09 17:34 UTC, maryiasa commented on personal_dirs/maryiasa/lesson_12/lesson12_HW.txt
> +Возможность изменения стратегии, подходов в процессе работы над продуктом, дабы он оставался конкурентоспособным.
fixed

2022-02-09 20:03 UTC, merged