hw 12
eugene-okulik/QAP-05 pull request #12
Opened 2022-02-08 15:25 UTC by Brlinetta

2022-02-08 15:44 UTC, eugene-okulik requested changes

2022-02-08 15:44 UTC, eugene-okulik commented on personal_dirs/nikita_pakhomov/hw12
> +    благодаря чему команды могут быстро реагировать на изменения.
И как называются небольшие но удобные (не инкременты)?

2022-02-08 15:44 UTC, eugene-okulik commented on personal_dirs/nikita_pakhomov/hw12
> +        вынесения решения заказчиком или другим уполномоченным лицом принимается приложение или нет.
Смотрю, многие добавили этот четвертый пункт. Он, на самом деле, не уровень. Их три: модульное, интеграционное, системное.

2022-02-08 18:07 UTC, Brlinetta commented on personal_dirs/nikita_pakhomov/hw12
> +    благодаря чему команды могут быстро реагировать на изменения.
спринты ?

2022-02-09 11:45 UTC, eugene-okulik approved these changes

2022-02-09 11:45 UTC, merged