Vadim Maletski_HW-21
eugene-okulik/QAP-05 pull request #50
Opened 2022-03-11 09:34 UTC by vadison90125

2022-03-12 20:26 UTC, YaroslavBelaychuk commented on personal_dirs/vadim_maletski/test_homework_21.py
> +    assert cart.is_displayed()
Кнопка add to cart не видна, пока не наведёшь на товар курсором. У меня такой тест падал

2022-03-12 21:13 UTC, vadison90125 commented on personal_dirs/vadim_maletski/test_homework_21.py
> +    assert cart.is_displayed()
Перепроверю, но этот тест у меня прошёл.

2022-03-13 11:12 UTC, vadison90125 commented on personal_dirs/vadim_maletski/test_homework_21.py
> +    assert cart.is_displayed()
Ясно. У меня браузер открывает не на весь экран хром и кнопка add to cart видна. Когда хром на полный экран - кнопка не видна, поэтому надо нажимать на товар или да, наводить курсор.

2022-03-14 18:16 UTC, eugene-okulik requested changes
Все отлично кроме проверки добавления товара в корзину

2022-03-14 18:23 UTC, eugene-okulik commented on personal_dirs/vadim_maletski/test_homework_21.py
> +    cart = driver.find_element(By.CLASS_NAME, 'clearfix')
А, я понял. Ты проверяешь поп-ап, который появляется после добавления. Но класс у него все таки не уникальный для страницы. Но и проверить хорошо бы его содержимое. Хотя бы, что есть текст "Product successfully added to your shopping cart". А, в идеале, проверить, что тот товар, который ты добавлял, есть в этом поп-апе.

2022-03-16 11:35 UTC, eugene-okulik approved these changes

2022-03-16 11:35 UTC, merged