Yaroslav Belaychuk - Lesson 12 HW
eugene-okulik/QAP-05 pull request #7
Opened 2022-02-07 20:02 UTC by YaroslavBelaychuk

2022-02-07 20:38 UTC, eugene-okulik requested changes
Все хорошо. Один момент поправь только

2022-02-07 20:38 UTC, eugene-okulik commented on personal_dirs/yaroslav_belaychuk/Homework_12/HW_12.txt
> +так как учитываются новые требования пользователей.
В рассказе про эджайл важно упоминать спринты (короткие циклы разработки) и постепенное наращивание функционала (все начинается с минимально работающего приложения и на него постепенно наращивается новый функционал)

2022-02-09 09:49 UTC, YaroslavBelaychuk commented on personal_dirs/yaroslav_belaychuk/Homework_12/HW_12.txt
> +так как учитываются новые требования пользователей.
Поправил, думаю что так)

2022-02-09 11:41 UTC, eugene-okulik approved these changes

2022-02-09 11:45 UTC, merged